version: '3.6'

services:
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=attendee
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=secRET

  backend:
    image: kordondev/lager-melder:latest
    ports:
      - "8080:8080"
    command: sh -c 'echo "yo"'
    depends_on:
      - mysql
